### ISSUE TITLE
Small plate presser doesn't work

### ISSUE THREAD

**Issue by Aixler** [ThePansmith/Enigmatica2ExpertUnofficialSkyblock#10] opened 2023-05-25 10:51 UTC
**Modpack version**
Enigmatica 2 Expert Skyblock Unoffical - 1.3.7.3

**Issue**
Small plate presser doesn't work

**Logs**
 at net.minecraft.block.state.BlockStateContainer$StateImplementation.neighborChanged(BlockStateContainer.java:481) ~[awu$a.class:?]
        at net.minecraft.world.World.neighborChanged(World.java:551) ~[amu.class:?]
        at net.minecraft.world.World.notifyNeighborsOfStateChange(World.java:496) ~[amu.class:?]
        at net.minecraft.block.BlockRedstoneWire.updateSurroundingRedstone(BlockRedstoneWire.java:159) ~[atf.class:?]
        at net.minecraft.block.BlockRedstoneWire.neighborChanged(BlockRedstoneWire.java:341) ~[atf.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.neighborChanged(BlockStateContainer.java:481) ~[awu$a.class:?]
        at net.minecraft.world.World.neighborChanged(World.java:551) ~[amu.class:?]
        at net.minecraft.world.World.notifyNeighborsOfStateChange(World.java:495) ~[amu.class:?]
        at net.minecraft.block.BlockRedstoneWire.updateSurroundingRedstone(BlockRedstoneWire.java:159) ~[atf.class:?]
        at net.minecraft.block.BlockRedstoneWire.neighborChanged(BlockRedstoneWire.java:341) ~[atf.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.neighborChanged(BlockStateContainer.java:481) ~[awu$a.class:?]
        at net.minecraft.world.World.neighborChanged(World.java:551) ~[amu.class:?]
        at net.minecraft.world.World.notifyNeighborsOfStateChange(World.java:496) ~[amu.class:?]
        at net.minecraft.block.BlockRedstoneWire.updateSurroundingRedstone(BlockRedstoneWire.java:159) ~[atf.class:?]
        at net.minecraft.block.BlockRedstoneWire.neighborChanged(BlockRedstoneWire.java:341) ~[atf.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.neighborChanged(BlockStateContainer.java:481) ~[awu$a.class:?]
        at net.minecraft.world.World.neighborChanged(World.java:551) ~[amu.class:?]
        at net.minecraft.world.World.notifyNeighborsOfStateChange(World.java:496) ~[amu.class:?]
        at net.minecraft.world.World.notifyNeighborsRespectDebug(World.java:440) ~[amu.class:?]
        at net.minecraft.world.World.markAndNotifyBlock(World.java:381) ~[amu.class:?]
        at net.minecraft.world.World.setBlockState(World.java:361) ~[amu.class:?]
        at net.minecraft.block.BlockLever.onBlockActivated(SourceFile:168) ~[art.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_371]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_371]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more

**Comment by MirrorImageQS** [comment] 2023-06-17 21:16
I have determined that this is caused by the recipes for crushing Nether Ores in the [config/advRocketry/SmallPlatePress.xml](https://github.com/ThePansmith/Enigmatica2ExpertUnofficialSkyblock/blob/main/overrides/config/advRocketry/SmallPlatePress.xml) file. Nether Ores do not seem to be available in the pack currently, and so each of the inputs for these recipes fail to return items, despite the logs indicating the recipe being registered successfully (maybe something is disabling the items after Advanced Rocketry loads these recipes?).

Either way, deleting/commenting out the following recipes from that file appears to fix the issue. These are lines 320 through 383

- oreNetherAluminum
- oreNetherCopper
- oreNetherNickel
- oreNetherSilver
- oreNetherOsmium
- oreNetherUranium
- oreNetherIron
- oreNetherGold

**Comment by ThePansmith** [comment] 2023-06-19 18:14
Fixed in 1.3.8

**Closed as completed by ThePansmith** 2023-06-19 18:14 UTC
