### ISSUE TITLE
Crash using Small Plate Presser

### ISSUE THREAD

**Issue by DJSnake89** [ThePansmith/Enigmatica2ExpertUnofficialSkyblock#9] opened 2023-05-19 19:27 UTC
**Modpack version**
1.3.7.3

**Issue**
When triggering "Small Plate Presser" from advanced rocketry with a redstone repeater it makes the game crash. I couldn't get it to work with a button or a lever so tried it with a repeater which resulted in the crash.  I had the press placed over a aluminium sheetplate which was above a block of obsidian. tried looking for other ways to make the rods but the other ways need rods for its recipe.

**Logs**
(https://mclo.gs/5emfTkE)

**Comment by MirrorImageQS** [comment] 2023-06-17 21:18
I identified the cause and a workaround to this in #10. There are recipes containing invalid/disabled items in the config for this block.

**Comment by ThePansmith** [comment] 2023-06-19 18:14
Fixed in 1.3.8

**Closed as completed by ThePansmith** 2023-06-19 18:14 UTC
